services:
  - type: web
    name: n8n-mvp
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /healthz
    startCommand: sh -lc 'N8N_PORT=${PORT:-5678} exec n8n start'
    envVars:
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_HOST
        value: comomeveo-mvp.onrender.com
      - key: N8N_EDITOR_BASE_URL
        value: https://comomeveo-mvp.onrender.com/
      - key: WEBHOOK_URL
        value: https://comomeveo-mvp.onrender.com/
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: GENERIC_TIMEZONE
        value: UTC
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password

databases:
  - name: n8n-db
    plan: free
