services:
  - type: web
    name: n8n-mvp
    env: docker
    plan: free        # puedes cambiar a starter si necesitas más estabilidad
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_HOST
        # reemplaza después del primer deploy con tu dominio real de Render
        value: n8n-mvp.onrender.com
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-mvp.onrender.com/
      - key: WEBHOOK_URL
        value: https://n8n-mvp.onrender.com/
      - key: GENERIC_TIMEZONE
        value: UTC
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password

databases:
  - name: n8n-db
    plan: free
